sudo: required

language: elixir

elixir: 1.5.2

otp_release: 20.0

addons:
  postgresql: 9.4

services:
  - redis-server

script:
  - MIX_ENV=test mix do ecto.create, ecto.load, test --exclude external:true

dist: precise
